### PR TITLE
 Add missing CAN{1,2}, LPUART{1,2} modules; indexify CSE_PRAM, ADC{0,1}.{SC1,R} registers

### PR DESCRIPTION
**Pull request by jfhansen**
Edit: 'wip-' prefix has been removed from project name, and crate version has been set to 0.11.0.
S32K144 PAC generated with svd2rust v0.17.0. As stated in the svd2rust changelog, it generates far more compact and more generic code than previous versions.
I have made some modifications in the .svd file which includes, making CSE_PRAM EmbeddedRAM into an array. The same is done with ADC0 and ADC1 SC1 channel registers and Data Result Registers, R. CAN1 and CAN2 peripherals are also added as separate structs, so that these peripherals can be used. The same is done with LPUART1 and LPUART2.

### CODE REVIEW

**Comment by tmplt** [comment]
Is there a particular reason why #3 was closed?

**Comment by jfhansen** [comment]
Maybe I am just a github noob, but I had to commit the changes I made, which required a new pull request, right?

**Comment by tmplt** [comment]
Every pull requests tracks whatever branch you applied your changes to from your fork. In the case of #3, your `issue1` branch is tracked. Any changes you make on this branch: new commits, commit reorders, history rewrites, etc. will be reflected in the pull request. There is no need to create a new one.

I recommend you try it out: the crate is still named `wip-s32144` and its version isn't 0.11.0 throughout the commits in this PR. This is where you will have to rewrite history with `git rebase`. In case something goes wrong locally you can pull the history down again from your `issue1` branch.

Or if you'd rather not, [you can allow me to edit your PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by jfhansen** [comment]
Ah, okay. TIL. Should I just reopen #3 and commit the changes there?

**Comment by tmplt** [comment]
Either here or #3 works.

**Pull request closed without merging**
