### PR TITLE
Regenerate crate with svd2rust v0.14.0

### PR DESCRIPTION
**Pull request by tmplt**
This svd2rust release allows generated code to be compiled with a stable compiler (v1.31.0 and up).

Version bumped to v0.10.0.

### CODE REVIEW

**Comment by kjetilkjeka** [comment]
Thanks @Tmplt !

Would you mind also update the changelog stating the code has been generated with svd2rust 0.14, and include the upgrades in `Cargo.toml` relevant to the user of this library (if any?). Just put it under a 0.10 entry (and keep the unpublished entry) as I will release this on crates once this PR is merged.

**Comment by tmplt** [comment]
Done. Changes to `Cargo.toml` are done in e0ddb38. Do you want them in a separate commit?

**Comment by kjetilkjeka** [comment]
It's fine as is, thanks again!

These changes are now released on crates.io as version 0.10

**Comment by tmplt** [comment]
Cheers!

**Pull request merged**
